# Generated by Django 4.0.3 on 2022-04-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
